### ISSUE TITLE
User Story: Password Reset

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/recipe_blog_django#14]
As a **registered user who forgot my password**, I want **to reset my password**, so that **I can regain access to my account**

## Acceptance Criteria

- **Given** that I am on the login page

- **When** I click on the "Forgot password?" link and enter my email address

- **Then** I should receive an email with instructions on how to reset my password

## Tasks

 - [x] Task 1 – Add "Forgot password?" link on the login page

 - [x] Task 2 – Develop a form for users to enter their email address for password reset

 - [x] Task 3 – Send an email with a reset password link upon user request
