### ISSUE TITLE
User Story: Delete a Recipe

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/recipe_blog_django#20]
As a **user**, I want **to delete a recipe I have created**, so that **I can remove it from my collection**

## Acceptance Criteria

- **Given** that I am viewing one of my recipes

- **When** I click the "Delete" button

- **Then** I should see a confirmation prompt and be able to permanently delete the recipe

## Tasks

 - [x] Task 1 – Implement a "Delete" button on the recipe view page

 - [x] Task 2 – Develop a confirmation prompt for recipe deletion
 
 - [x] Task 3 – Implement backend functionality to remove the recipe from the database
