### ISSUE TITLE
User Story: Install Django and supporting libraries

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/recipe_blog_django#8]
As a **Developer**, I want to **set up Django and install the supporting libraries predicted to be needed**, so that **I am ready to start development**

## Tasks
- [x] Task 1 – Install Django
- [x] Task 2 – Install gunicorn
- [x] Task 3 – Install allauth
- [x] Task 4 – Create a requirements.txt file
- [x] Task 5 – Create the Django project – called recipe_project
- [x] Task 6 – Create the first app – called recipe_blog and add it to the installed apps in the settings.py
